---
title: "Data 607 - Project 4"
author: "Glen Dale Davis"
date: "2023-04-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load Required Packages:

```{r packages, warning=FALSE, message=FALSE}
library(tidyverse)
library(tidytext)
library(textdata)
library(rpart)
library(rpart.plot)

```

### Load Poetry and Short Story Data:

```{r data}
completed <- readLines("completed.txt") 
if (length(completed) == 0){
    files <- list.files(pattern = "^P_.+\\.txt$|^SS_.+\\.txt$")
    txt_df <- as.data.frame(matrix(nrow = 0, ncol = 6))
    cols <- c("category", "collection", "author", "title", "author_title", "lines")
    colnames(txt_df) <- cols
    for (i in 1:length(files)){
        extraction <- str_replace_all(files[i], "_", " ")
        p <- "(?<cat>P|SS)[- ](?<coll>.+)(?<by> by )(?<auth>.+)(?<ftype> Altered\\.txt)"
        extraction <- str_match(extraction, p)
        category <- extraction[1, 2]
        collection <- extraction[1, 3]
        author <- extraction[1, 5]
        txt <- trimws(readLines(files[i]), which="left")
        txt <- as.data.frame(txt)
        write(files[i], file = "completed.txt", append = TRUE)
        dlim <- txt[1, 1]
        if (dlim == "+"){
            starting_line <- str_detect(txt[, 1], "^\\+$")
        }else if (dlim == "="){
            starting_line <- str_detect(txt[, 1], "^=$")
        }
        for (i in nrow(txt):1){
            if (i == nrow(txt)){
                end <- i
            }
            if (starting_line[i]){
                start <- i + 1
                content <- txt[start:end, 1]
                title <- content[1]
                author_title <- paste(author, title, sep = "_")
                lines <- content[2:length(content)]
                #we want to preserve meaningful line breaks throughout the text
                #but eliminate leading or tailing sequences of them; process follows
                non_empty <- lines != ""
                #find index of first TRUE in vector of whether lines are not empty
                x <- which.max(non_empty) 
                lines <- lines[x:length(lines)] #trim empty lines from front only
                rev_lines <- rev(lines) #reverse lines so we can trim from back
                y <- which.max(rev(non_empty)) 
                rev_lines <- rev_lines[y:length(rev_lines)] #trim from back
                lines <- rev(rev_lines) #put lines back in proper order
                addition <- cbind(category, collection, author, title,
                                  author_title, lines)
                txt_df <- rbind(txt_df, addition)
                end <- i - 1
            }else{
                next
            }
        }
    }
    txt_df$line_num <- as.integer(ave(txt_df$lines, txt_df$author_title, FUN = seq_along))
    txt_pivot <- txt_df %>%
        pivot_wider(names_from = line_num, names_prefix = "line_" ,
                values_from = lines)
    write.csv(txt_df, file = "txt_df.csv", row.names = FALSE)
    write.csv(txt_pivot, file = "txt_pivot.csv", row.names = FALSE)
}else{
    my_url1 <- "https://raw.githubusercontent.com/geedoubledee/data607_project4/main/txt_df.csv"
    txt_df <- read.csv(my_url1)
    my_url2 <- "https://raw.githubusercontent.com/geedoubledee/data607_project4/main/txt_pivot.csv"
    txt_pivot <- read.csv(my_url2)
}

```

```{r sentiments}
nrc <- get_sentiments("nrc")
cols <- c("word", "sentiment_nrc")
colnames(nrc) <- cols
bing <- get_sentiments("bing")
cols <- c("word", "sentiment_bing")
colnames(bing) <- cols

```

```{r set_seed}
set.seed(6001)

```

```{r shuffle_the_data}
txt_shuffle <- txt_pivot
shuffle <- sample(1:nrow(txt_shuffle))
txt_shuffle <- txt_shuffle[shuffle, ]
txt_shuffle$category <- ifelse(txt_shuffle$category == "SS", 1, 0)
remove <- c("collection", "author", "title")
txt_shuffle <- txt_shuffle[, !colnames(txt_shuffle) %in% remove]

```

```{r count_punctuation}
txt_punct <- txt_shuffle
txt_punct[txt_punct == ""] <- NA
txt_punct <- txt_punct %>%
    mutate(across(starts_with("line_"), \(x) str_count(x, "[[:punct:]]"))) %>%
    mutate(total_punct = rowSums(select(., starts_with("line_")), na.rm = TRUE)) %>%
    mutate(total_non_empty_lines = rowSums(!is.na(select(.,
                                                         starts_with("line_"))))) %>%
    select(!starts_with("line_"))

```

```{r count_words}
txt_words <- txt_df
remove <- c("category", "collection", "author", "title")
txt_lines <- txt_words[, !colnames(txt_words) %in% remove]
txt_lines <- txt_lines %>%
    group_by(author_title) %>%
    summarize(total_lines = max(line_num))
txt_words <- txt_words[, !colnames(txt_words) %in% remove]
txt_words <- txt_words %>%
    unnest_tokens(word, lines)

```

```{r analyze_sentiments}
txt_sentiments <- txt_words %>%
    left_join(nrc, by = join_by(word), multiple = "all") %>%
    left_join(bing, by = join_by(word), multiple = "all") %>%
    mutate(sentiment = coalesce(sentiment_nrc, sentiment_bing))
remove <- c("sentiment_nrc", "sentiment_bing")
txt_sentiments <- txt_sentiments[, !colnames(txt_sentiments) %in% remove]
txt_emotions <- txt_sentiments %>%
    filter(!sentiment %in% c("positive", "negative") & !is.na(sentiment)) %>% 
    group_by(author_title, sentiment) %>%
    summarize(sentiment_count = n())
emotions_pivot <- txt_emotions %>%
    pivot_wider(names_from = sentiment, values_from = sentiment_count)
emotion_totals <- txt_emotions %>%
    group_by(author_title) %>%
    summarize(emotion_total = sum(sentiment_count)) %>%
    left_join(emotions_pivot, by = join_by(author_title)) %>%
    mutate(percent_anger = anger / emotion_total,
           percent_anticipation = anticipation / emotion_total,
           percent_disgust = disgust / emotion_total,
           percent_fear = fear / emotion_total,
           percent_joy = joy / emotion_total,
           percent_sadness = sadness / emotion_total,
           percent_surprise = surprise / emotion_total,
           percent_trust = trust / emotion_total)
emotion_totals[is.na(emotion_totals)] <- 0
txt_polarity <- txt_sentiments %>%
    filter(sentiment %in% c("positive", "negative")) %>%
    group_by(author_title, sentiment) %>%
    summarize(sentiment_count = n())
polarity_pivot <- txt_polarity %>%
    pivot_wider(names_from = sentiment, values_from = sentiment_count)
polarity_totals <- txt_polarity %>%
    group_by(author_title) %>%
    summarize(polarity_total = sum(sentiment_count)) %>%
    left_join(polarity_pivot, by = join_by(author_title)) %>%
    mutate(percent_neg = negative / polarity_total,
           percent_pos = positive / polarity_total)
polarity_totals[is.na(polarity_totals)] <- 0

```

```{r count_lines_that_rhyme_w_1_prev_or_2_prev}
my_url3 <- "https://raw.githubusercontent.com/geedoubledee/data607_project4/main/cmudict_0_7b.txt"
cmudict <- readLines(my_url3)
cmudict <- as.data.frame(cmudict[-c(1:56)])
colnames(cmudict) <- "word"
cmudict <- cmudict %>%
    separate_wider_delim(cols = word, delim = "  ", names_sep = "_",
                         too_few = "align_start")
colnames(cmudict) <- c("word", "pronunciation")
cmudict$word <- str_to_lower(str_replace_all(cmudict$word, "[[:punct:]]", ""))
cmudict$start_index <- sapply(gregexpr("[A-Z]{2}1", cmudict$pronunciation),
                                      function(x) rev(x)[1])
cmudict <- cmudict %>%
    mutate(rhyming_phoneme = substr(.$pronunciation, start_index, 1000000L))
txt_words$author_title_line_num <- paste(txt_words$author_title,
                                         txt_words$line_num, sep = "_")
txt_words$word_num <- as.integer(ave(txt_words$word, txt_words$author_title_line_num,
                                     FUN = seq_along))
remove <- "author_title_line_num"
txt_words <- txt_words[, !colnames(txt_words) %in% remove]

if (!"txt_rhymes.csv" %in% completed){
    txt_rhymes <- txt_words %>%
        group_by(author_title, line_num) %>%
        top_n(1, word_num) %>%
        left_join(cmudict, by = join_by(word), multiple = "first") %>%
        mutate(rhymes_1_line_prev = 0, rhymes_2_line_prev = 0)
    remove <- c("pronunciation", "start_index")
    txt_rhymes <- txt_rhymes[, !colnames(txt_rhymes) %in% remove]
    for (i in 2:nrow(txt_rhymes)){
        if (is.na(txt_rhymes[i, 5]) | 
            is.na(txt_rhymes[(i-1), 5]) | 
            txt_rhymes[i, 5] != txt_rhymes[(i-1), 5]){
            next
        }else{
            if (txt_rhymes[i, 1] != txt_rhymes[(i-1), 1]){
                next
            }else{
                txt_rhymes[i, 6] <- 1
            }
        }
    }
    for (i in 3:nrow(txt_rhymes)){
        if (is.na(txt_rhymes[i, 5]) | 
            is.na(txt_rhymes[(i-2), 5]) | 
            txt_rhymes[i, 5] != txt_rhymes[(i-2), 5]){
            next
        }else{
            if (txt_rhymes[i, 1] != txt_rhymes[(i-2), 1]){
                next
            }else{
                txt_rhymes[i, 7] <- 1
            }
        }
    }
    write.csv(txt_rhymes, "txt_rhymes.csv", row.names = FALSE)
}else{
    my_url4 <- "https://raw.githubusercontent.com/geedoubledee/data607_project4/main/txt_rhymes.csv"
    txt_rhymes <- read.csv(my_url4)
}





```

```{r create_numeric_summary}
txt_summary <- txt_words %>%
    group_by(author_title) %>%
    summarize(word_count = n()) %>%
    left_join(txt_lines, by = join_by(author_title)) %>%
    left_join(txt_punct, by = join_by(author_title)) %>%
    left_join(emotion_totals, by = join_by(author_title)) %>%
    left_join(polarity_totals, by = join_by(author_title))
txt_summary$total_lines <- as.integer(txt_summary$total_lines)
remove <- c("emotion_total", "polarity_total", "anger", "anticipation", "disgust",
            "fear", "joy", "sadness", "surprise", "trust", "positive", "negative")
txt_summary <- txt_summary[, !colnames(txt_summary) %in% remove]
txt_summary <- txt_summary %>%
    mutate(words_per_non_empty_lines = word_count / total_non_empty_lines) %>%
    mutate(punct_per_non_empty_lines = total_punct / total_non_empty_lines)

```



```{r train_test_dataset}
#process adapted from https://www.guru99.com/r-decision-trees.html
split_data_into_test_train <- function(data, size = 0.7, train = TRUE){
    n_row <- nrow(data)
    split_n_row <- size * n_row
    split <- 1: split_n_row
    if (train == TRUE){
        return (data[split, ])
    } else {
        return (data[-split, ])
    }
}
train <- split_data_into_test_train(txt_summary, size = 0.7, train = TRUE)
train <- train %>%
    column_to_rownames(var="author_title")
test <- split_data_into_test_train(txt_summary, size = 0.7, train = FALSE)
test <- test %>%
    column_to_rownames(var="author_title")
fit <- rpart(category~., data = train, method = 'class')
rpart.plot(fit, extra = 106)

```